# Generated by Django 3.2.9 on 2021-12-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_caso', models.CharField(max_length=50)),
                ('nombre_caso', models.CharField(max_length=50)),
                ('nombre_empresa', models.CharField(max_length=50)),
            ],
        ),
    ]
